# site settings
title: lập trình demo
subtitle: thông tin lập trình website
email: Doanphuxm01@gmail.com
description:lập trình cho tương lai bạn <br /> thế giới công nghệ đang cần bạn .
baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
url: "codemax.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 100000
country: United States of America
phone: +84 92 9387599

# social settings
500px_url:
facebook_url:
github_url: https://github.com/andrewbanchich
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
